### PR TITLE
Add configurable message marshaller

### PR DESCRIPTION
**Pull request by marvec**

### CODE REVIEW

**Comment by marvec** [comment]
This is a simple solution for issue #25

**Comment by marvec** [comment]
Your Travis build is failing because it uses very old JDK no longer supported.

**Comment by kn100** [comment]
You know what's amusing? I was literally having a conversation yesterday saying that we should probably allow exactly this. I'll review your PR once I get some time, so thanks for doing this!

**Comment by marvec** [comment]
Glad to hear that. I submitted this late in the night, so maybe, with a fresh mind, the name of the interface could be smarter, could have some default implementation and the setter method could stick with the original name for backwards API compatibility. Just let me know if you wanted these changes, I can do that.

**Comment by marvec** [comment]
Hello, any progress on this?

**Comment by kn100** [comment]
Hey marvec,

We're currently working on a new feature in this library (now in PR) - and as part of it it'll be fixing the build pipeline. Mind waiting for us to get that out the door and then rebasing this so the Travis build works? 

Thanks for your patience and thanks again for the PR.

**Comment by kn100** [comment]
I am investigating this today.

**Comment by kn100** [comment]
@marvec We've fixed the build process and I *finally* got around to looking at this PR. I've made a couple changes. Mind letting me know if it still solves your problem in its current form? Any comments on style or similar? If not I'll merge and get this out very soon!

**Pull request merged**
